### ISSUE TITLE
如何使用网络图片？

### ISSUE THREAD

**Issue by feilongproject** [xh321/LiteLoaderQQNT-Background-Plugin#11]
RT，如果想在每一次打开NTQQ时使用不同的网络随机图，并且想对页面内部放置一个可以刷新背景图片的按钮（和随机图一起使用），能否实现？

**Comment by xh321** [comment]
可以实现，我做好了通知你
你的意思大概是那种api吧，每次获取不同的图片？比如必应壁纸api。

**Comment by feilongproject** [comment]
> 可以实现，我做好了通知你
> 你的意思大概是那种api吧，每次获取不同的图片？比如必应壁纸api。

差不多，自定义最好了，比如能随机色图什么的（x

**Comment by xh321** [comment]
> > 可以实现，我做好了通知你
> > 你的意思大概是那种api吧，每次获取不同的图片？比如必应壁纸api。
> 
> 差不多，自定义最好了，比如能随机色图什么的（x

OK

**Comment by xh321** [comment]
基础可用的版本已更新，将会持续优化（例如支持JSON返回的API等），如有问题请持续留言~
