### ISSUE TITLE
聊天窗口昵称字体不正确

### ISSUE THREAD

**Issue by LittleChest** [xh321/LiteLoaderQQNT-Background-Plugin#12]
环境：Windows 11
QQNT版本：9.8.5-14086
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/81231195/4c4f1c26-e554-401d-8a96-3945bcf8b5d1)
字体周围像是有白边一样 模糊

**Comment by xh321** [comment]
你好，这是预期效果，是mix-blend-mode的效果，因为如果背景透明的话字可能看不清，所以加了这么一个效果来让文字自动反色，web在渲染的时候可能是有这么一个问题。

**Comment by Natsukage** [comment]
这个效果在有群友或者自己的昵称有emoji时候会非常阴间……（整个昵称都反色了）
user-name > span
和
.group-user__name.text-ellipsis
都会受到这个的影响。

**Comment by xh321** [comment]
确实是已知的问题，我自己也知道显示出来不太好，但是还是没有什么好的替代方案，毕竟还要能看清文字。是否在这些文字背景上加上一些不透明度会比当前效果好一些？

**Comment by Natsukage** [comment]
> 确实是已知的问题，我自己也知道显示出来不太好，但是还是没有什么好的替代方案，毕竟还要能看清文字。是否在这些文字背景上加上一些不透明度会比当前效果好一些？

不太清楚目前插件能做到什么程度。现在的user-name 中只有一个span，包含了用户名的全名。
如果可以在显示之前对user-name进行处理，将emoji和普通文字拆分成不同的span，然后只对text适用mix-blend-mode，而对emoji保持原样显示的话，应该可以避免这个问题
<div class="user-name">
  <span class="text">这是昵称的文字部分</span>
  <span class="emoji">🙂</span>
  <span class="text">这是昵称的后面部分</span>
</div>
因为emoji本身是包含颜色的，即使有背景也不需要担心看不清的问题。

但是如果目前插件能够实现的功能上做不到这点的话，就比较麻烦了，可能加上不透明度会更好一些。
或者允许用户根据图片自定义，自己选择一个自己看得清文字的背景图片上的不透明度之类的（

**Comment by xh321** [comment]
> > 确实是已知的问题，我自己也知道显示出来不太好，但是还是没有什么好的替代方案，毕竟还要能看清文字。是否在这些文字背景上加上一些不透明度会比当前效果好一些？
> 
> 不太清楚目前插件能做到什么程度。现在的user-name 中只有一个span，包含了用户名的全名。 如果可以在显示之前对user-name进行处理，将emoji和普通文字拆分成不同的span，然后只对text适用mix-blend-mode，而对emoji保持原样显示的话，应该可以避免这个问题
> 
> ```
> <div class="user-name">
>   <span class="text">这是昵称的文字部分</span>
>   <span class="emoji">🙂</span>
>   <span class="text">这是昵称的后面部分</span>
> </div>
> ```
> 
> 因为emoji本身是包含颜色的，即使有背景也不需要担心看不清的问题。
> 
> 但是如果目前插件能够实现的功能上做不到这点的话，就比较麻烦了，可能加上不透明度会更好一些。 或者允许用户根据图片自定义，自己选择一个自己看得清文字的背景图片上的不透明度之类的（

不方便拆分，拆分需要用到js，会监听dom变动，造成一定性能损耗，而这是没必要的。我觉得确实还是设置背景不透明度比较好

**Comment by xh321** [comment]
目前已经更新了一个版本，可以看看是否正常

**Comment by Natsukage** [comment]
> 目前已经更新了一个版本，可以看看是否正常

现在显示效果没问题了，感谢！
