### ISSUE TITLE
亮色模式下，昵称不显示

### ISSUE THREAD

**Issue by xiaozhangup** [xh321/LiteLoaderQQNT-Background-Plugin#13]
![图片](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/68374769/7fbc1b63-132a-4d58-ab63-9320f5cdb35c)

除此之外，还有一个细节问题
![图片](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/68374769/1599253d-e923-4127-9f22-b103e085c956)

很显然这里幼儿个裂缝

**Comment by xh321** [comment]
先回答裂缝，这个应该是计算的浮点误差，你可以重新调整一下窗口大小，可以看到裂缝也会移动，这个估计是QQ计算div宽度高度的时候有一点点误差。不装插件的时候，你看不出来，因为没有透明。装了插件，这种误差就很明显了。
总结就是：我认为没法解决，是QQ自己的问题。
然后昵称不显示可能是CSS的一点兼容性问题，你是什么系统呢？

**Comment by xiaozhangup** [comment]
> 先回答裂缝，这个应该是计算的浮点误差，你可以重新调整一下窗口大小，可以看到裂缝也会移动，这个估计是QQ计算div宽度高度的时候有一点点误差。不装插件的时候，你看不出来，因为没有透明。装了插件，这种误差就很明显了。 总结就是：我认为没法解决，是QQ自己的问题。 然后昵称不显示可能是CSS的一点兼容性问题，你是什么系统呢？

Fedora

**Comment by xh321** [comment]
> > 先回答裂缝，这个应该是计算的浮点误差，你可以重新调整一下窗口大小，可以看到裂缝也会移动，这个估计是QQ计算div宽度高度的时候有一点点误差。不装插件的时候，你看不出来，因为没有透明。装了插件，这种误差就很明显了。 总结就是：我认为没法解决，是QQ自己的问题。 然后昵称不显示可能是CSS的一点兼容性问题，你是什么系统呢？
> 
> Fedora 38 缩放了一下窗口，那个缝好像没动

Linux我暂时没环境，不过这个css属性我后面会去掉，你可以等待下一个版本看看；裂缝的问题，我应该是解决不了

**Comment by xh321** [comment]
目前已经更新了一个版本，可以看看文字是否恢复

**Comment by xh321** [comment]
如果没问题的话先关闭ISSUE了，还有问题欢迎随时reopen。
