### ISSUE TITLE
如何设置透明度

### ISSUE THREAD

**Issue by fgr178707** [xh321/LiteLoaderQQNT-Background-Plugin#14]
我想问一下怎么设置透明度 改配置文件?
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/109357981/c90ce276-0b3e-4635-a77a-232306b9af9b)

**Comment by xh321** [comment]
目前透明度都是预设好的，可以自行修改renderer.js下半部分的css。
因为涉及的组件实在是太多了，麻烦自己修改一下，具体组件的css类名请安装调试组件（chii-devtools）后F12查看一下class。
