### ISSUE TITLE
[Feature] 在收藏页面应用背景图片

### ISSUE THREAD

**Issue by frg2089** [xh321/LiteLoaderQQNT-Background-Plugin#15]
## 预期行为
在收藏页（QQ左侧栏倒数第二个）中应用背景

## 当前行为
不会应用背景图片
在应用`MSpring Theme`的情况下 这个页面没有遮罩 会看不清字

## 版本
插件版本: 0.1.9
LiteLoader: 0.5.0
QQNT: 9.9.1-15489
Chromium: 114.0.5735.243
Electron: 25.3.1
Node.js 18.15.0

**Comment by xh321** [comment]
收藏修了，但是其他地方可能还有不尽如人意的地方，目前已向MSpring作者提了意见，等待后续更新
