### ISSUE TITLE
[BUG] 表情界面窗口层级错误

### ISSUE THREAD

**Issue by frg2089** [xh321/LiteLoaderQQNT-Background-Plugin#16]
我在用这个插件的时候出现了与 #1 相同的问题

插件版本: 0.1.9

**Comment by xh321** [comment]
是否还安装了其他插件，能否关闭其他插件再试试，然后逐一打开，看看是和哪个插件不兼容？（注意关闭或开启插件需要重启qq）
我这里最新版QQ没有遇到问题。

**Comment by frg2089** [comment]
在禁用了除了背景图片以外的所有插件之后还是有这个问题
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/42184238/e0de9931-a0b3-4924-b140-79b1f4d6dda5)
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/42184238/542ddc1b-29e2-473e-8fd2-faf49b44a10a)

**Comment by frg2089** [comment]
https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/blob/b8123b490664f9fd11836d994fe6e219c5b818cb/renderer.js#L925-L927
https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/blob/b8123b490664f9fd11836d994fe6e219c5b818cb/renderer.js#L1216-L1218

我把它们改成这样后修复了问题
```css
.chat-msg-area__vlist, #ml-root{
  z-index:unset!important;
}
```
#ml-root有一个z-index: 1;的样式

**Comment by xh321** [comment]
> https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/blob/b8123b490664f9fd11836d994fe6e219c5b818cb/renderer.js#L925-L927
> 
> 
> https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/blob/b8123b490664f9fd11836d994fe6e219c5b818cb/renderer.js#L1216-L1218
> 
> 我把它们改成这样后修复了问题
> 
> ```css
> .chat-msg-area__vlist, #ml-root{
>   z-index:unset!important;
> }
> ```
> 
> #ml-root有一个z-index: 1;的样式

好的，我会修改的

**Comment by xh321** [comment]
新版本已推送
