### ISSUE TITLE
[BUG] 好友选项卡页面背景太亮

### ISSUE THREAD

**Issue by frg2089** [xh321/LiteLoaderQQNT-Background-Plugin#17]
好友选项卡页面在选中好友或群聊后没有遮罩会看不清字

**Comment by xh321** [comment]
你是指和MSpring的兼容性对吧，这个需要等待他们那给出方案

**Comment by xh321** [comment]
> 你是指和MSpring的兼容性对吧，这个需要等待他们那给出方案

原因是本插件和MSpring均修改了同一个地方，导致互相冲突

**Comment by frg2089** [comment]
> > 你是指和MSpring的兼容性对吧，这个需要等待他们那给出方案
> 
> 原因是本插件和MSpring均修改了同一个地方，导致互相冲突

emm...我记得LiteLoaderQQNT有全局挂载LiteLoader对象
就...能不能通过这种东西来实现兼容...？
比如在这里看到别的插件就禁用某些功能啥的
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/42184238/e167fa07-ee86-4011-86ca-c8c8b3b269f6)

**Comment by xh321** [comment]
> > > 你是指和MSpring的兼容性对吧，这个需要等待他们那给出方案
> > 
> > 
> > 原因是本插件和MSpring均修改了同一个地方，导致互相冲突
> 
> emm...我记得LiteLoaderQQNT有全局挂载LiteLoader对象 就...能不能通过这种东西来实现兼容...？ 比如在这里看到别的插件就禁用某些功能啥的 ![image](https://user-images.githubusercontent.com/42184238/258582759-e167fa07-ee86-4011-86ca-c8c8b3b269f6.png)

这个需要MSpring那边去做适配啦，底层细节是，他的主题插件会把所有背景删除，而我这个背景插件会加一层半透明背景以免看不清。是他的插件把我加的半透明背景也给删了。这个只能他那边做一下适配

**Comment by xh321** [comment]
> > > > 你是指和MSpring的兼容性对吧，这个需要等待他们那给出方案
> > > 
> > > 
> > > 原因是本插件和MSpring均修改了同一个地方，导致互相冲突
> > 
> > 
> > emm...我记得LiteLoaderQQNT有全局挂载LiteLoader对象 就...能不能通过这种东西来实现兼容...？ 比如在这里看到别的插件就禁用某些功能啥的 ![image](https://user-images.githubusercontent.com/42184238/258582759-e167fa07-ee86-4011-86ca-c8c8b3b269f6.png)
> 
> 这个需要MSpring那边去做适配啦，底层细节是，他的主题插件会把所有背景删除，而我这个背景插件会加一层半透明背景以免看不清。是他的插件把我加的半透明背景也给删了。这个只能他那边做一下适配

如果着急的话，你也可以在那边提一下issue催一下（

**Comment by frg2089** [comment]
倒是没那么着急（

**Comment by MUKAPP** [comment]
[MSpring Theme 1.1.0 - 优化开启 背景插件 之后的样式](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/releases/tag/v1.1.0#:~:text=3b65f84-,%E4%BC%98%E5%8C%96%E5%BC%80%E5%90%AF%20%E8%83%8C%E6%99%AF%E6%8F%92%E4%BB%B6%20%E4%B9%8B%E5%90%8E%E7%9A%84%E6%A0%B7%E5%BC%8F,-%E4%BC%98%E5%8C%96%E5%BC%80%E5%90%AF)
