### ISSUE TITLE
消息栏上下滚动有延迟，好像是性能问题……

### ISSUE THREAD

**Issue by T7imal** [xh321/LiteLoaderQQNT-Background-Plugin#19]
开启背景后，使用核显运行时，消息栏上下滚动有明显延迟、不跟手的现象。使用独显运行后解决。

不过作为（电池快报废的）游戏本用户，用独显还是太耗电了，希望能够改进，谢谢！

CPU：11800h
显卡：3060 laptop
系统：Win10 专业版 22H2

**Comment by xh321** [comment]
猜测是消息列表开启磨砂效果的缘故？目前支持关闭该效果，可以前往设置里关闭后再看看是不是缓解？

**Comment by T7imal** [comment]
> 猜测是消息列表开启磨砂效果的缘故？目前支持关闭该效果，可以前往设置里关闭后再看看是不是缓解？

磨砂效果指的是毛玻璃效果吗？我对比了开关毛玻璃效果的表现，确实关闭时更流畅一些。不过依然不如使用独显时，或不使用该插件时的流畅程度（跑不满165帧？）。

**Comment by T7imal** [comment]
刚刚误操作了，抱歉。

磨砂效果指的是毛玻璃效果吗？我对比了开关毛玻璃效果的表现，确实关闭时更流畅一些，但是依然不如使用独显，或者不使用该插件时的流畅程度（跑不满165帧？）。

**Comment by T7imal** [comment]
我用任务管理器对比了一下不同情况下的gpu占用，测试方法为不断上下滚动消息栏

- 纯核显运行，不开启背景插件，核显占用率20%~30%
- 纯核显运行，不开启背景插件，核显占用率65%~75%
- 独显运行，不开启背景插件，核显占用率30%~40%，独显占用率25%~35%
- 独显运行，开启背景插件，核显占用率30%~40%，独显占用率15%~25%

以上测试均未开启毛玻璃效果，使用独显运行的方法是 win10 图形设置，选择QQ为高性能，实际测试核显与独显都在出力。

**Comment by xh321** [comment]
开背景透明是会增加GPU占用的，如果要跑满165帧是不是要求太高了（
这个我也不清楚怎么优化啦

**Comment by xh321** [comment]
暂时没有更好的办法，我先关闭issue了。
