### ISSUE TITLE
可以支持MP4之类的视频文件吗

### ISSUE THREAD

**Issue by zyy515** [xh321/LiteLoaderQQNT-Background-Plugin#20]
可以添加一些新的文件格式支持吗，比如视频类的，例如MP4这种文件，动图的话看起来效果会更好一些

**Comment by xh321** [comment]
考虑添加。动图的话（例如GIF），有那么大分辨率的吗，如果是视频差不多

**Comment by xh321** [comment]
最新版已支持，同时需要更新框架到1.0.3版本。试试看？

**Comment by zyy515** [comment]
谢谢，效果很好
