### ISSUE TITLE
表情面板碎掉了

### ISSUE THREAD

**Issue by PIndividual** [xh321/LiteLoaderQQNT-Background-Plugin#22]
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/62368342/d4016c07-af20-47a3-b7d0-435d13b280c2)

**Comment by xh321** [comment]
检查插件冲突，把其他插件都关了试试看？另外说一下QQ版本和什么系统

**Comment by xh321** [comment]
如果长期不回复的话issue先关闭了，还有问题的话你可以试试用F12看看，是哪个类把表情面板的透明度改为0了。你可以关闭背景插件对比一下，我猜测并不是我这个插件导致的问题。
