### ISSUE TITLE
启用此插件会导致消息框右侧滚动条出现混乱

### ISSUE THREAD

**Issue by DeliciousLiMiao** [xh321/LiteLoaderQQNT-Background-Plugin#24]
![QQ截图20231220123326](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/37429826/41d5ca2e-3c3d-4e5d-9b9d-a13c9115b598)
滚动条滚轮使用正常，但长按滚动条时会出现滚动条一直向上滑动，直到滚动条消失
![GIF 2023-12-20 12-40-51](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/37429826/6bfa5d0a-9636-4916-9522-a49649f71e13)

**Comment by xh321** [comment]
0.1.15已修复，但偶发性会出现拖不动的情况，这时重新进入聊天区域就正常了
