### ISSUE TITLE
关于1.0.0版本的适配

### ISSUE THREAD

**Issue by GrassCarpxD** [xh321/LiteLoaderQQNT-Background-Plugin#26]
https://t.me/LiteLoaderQQNT_Channel/3

1.0.0版本不向下兼容插件，请求适配

**Comment by xh321** [comment]
收到，将会于近期适配

**Comment by kirietuan** [comment]
麻烦加速适配 么么

> 收到，将于近期推出

**Comment by xh321** [comment]
已适配，并在16183上测试
若新版本QQ测试有问题请开新issue。
