### ISSUE TITLE
大佬大佬 能不能实现用动态壁纸api作为背景呢

### ISSUE THREAD

**Issue by kirietuan** [xh321/LiteLoaderQQNT-Background-Plugin#28]
首先感谢适配了1.0
然后我试了几个动态壁纸或者视频的api 都不行 咱能不能实现呢 可以赞助大佬😘

**Comment by xh321** [comment]
动态壁纸指的是视频吗，api返回的是mp4文件流这样？我可以试试做适配，这几天就做

**Comment by kirietuan** [comment]
> 动态壁纸指的是视频吗，api返回的是mp4文件流这样？我可以试试做适配，这几天就做

爱你 么么
提供一个api试试
这个好像是webm的格式https://api.qiuliqi.top/sp/
但是一般来说就那几个视频格式

**Comment by xh321** [comment]
最新版已支持，同时需要更新框架到1.0.3版本。试试看？

**Comment by kirietuan** [comment]
> 最新版已支持，同时需要更新框架到1.0.3版本。试试看？

测试了一下 没问题 非常奈斯么么
