### ISSUE TITLE
QQ视频背景同时占用内存与专用显存

### ISSUE THREAD

**Issue by shi-an** [xh321/LiteLoaderQQNT-Background-Plugin#29]
并且每打开一个窗口都会再次加载数据
![0e975c25d163257858cb16e2e6df13f0](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/79352488/d277858b-a661-4f19-a044-1f2a87b8c6ae)
![b79149ec3db689ce8c5f2ad96f2433ce](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/79352488/c10ed190-9d21-4beb-aa3b-12e618aa0cb5)

**Comment by xh321** [comment]
目前是这样的，因为现在实现原理是在背景上加一个video控件，而新窗口只能加新video，还没有查到更好的解决办法。如果你使用的是单独聊天窗口，每个窗口一个video标签，同时如果视频过大是会导致内存和解码压力很大的，就好像你同时开五六个浏览器窗口同时播放视频一样，你可以试一下看看浏览器的内存占用和GPU占用。
