### ISSUE TITLE
两个建议!!

### ISSUE THREAD

**Issue by AkatsukiZhang** [xh321/LiteLoaderQQNT-Background-Plugin#30]
1. 
> 因为自己的图片收藏按年份分了几个子文件夹，
> 插件无法读取到子文件夹内的文件。
> 希望可以更新支持一下目录里的子文件夹！
2. 
> 网络API链接有一些是返回JSON格式的文本，
> > 例如[Lolicon API](https://api.lolicon.app/)
> 这样插件无法加载图片

**Comment by xh321** [comment]
最新版已解决

**Comment by AkatsukiZhang** [comment]
啊...我还在编辑第二个，是关于网络API链接的！
好快的回复(x

**Comment by AkatsukiZhang** [comment]
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/22972499/571ed89b-6e5e-415b-b8b7-6635066ea6be)
啊，更新报错了欸？

**Comment by xh321** [comment]
刚刚刷新页面，才发现你又更新了第二个需求哇，第二个JSON需求会在后面的版本更新。至于你这个更新报错，看看是不是网络问题？我上传的zip应该是没问题的

**Comment by xh321** [comment]
更新出问题的情况已经解决

**Comment by AkatsukiZhang** [comment]
好的，更新成功了！
期待网络API链接的更新！
感谢！

**Comment by xh321** [comment]
JSON 返回支持也已更新，使用最新版即可

**Comment by AkatsukiZhang** [comment]
更新试了下，可以了!
另外还想说一个，是否可以提供一个选项，可以保存从Api获取的图片到指定目录？

最后还有一个问题，就是每次打开新的界面(例如查看图片的界面)背景图也会加载一个新的，
如果是使用本地图片倒也不是什么大问题，如果过于频繁地使用API的会不会有其他的风险?
有没有风险我不是很了解啦，是否需要多加一个限制，使用API时让多个界面共用当前的背景图片？

**Comment by xh321** [comment]
> 更新试了下，可以了! 另外还想说一个，是否可以提供一个选项，可以保存从Api获取的图片到指定目录？
> 
> 最后还有一个问题，就是每次打开新的界面(例如查看图片的界面)背景图也会加载一个新的， 如果是使用本地图片倒也不是什么大问题，如果过于频繁地使用API的会不会有其他的风险? 有没有风险我不是很了解啦，是否需要多加一个限制，使用API时让多个界面共用当前的背景图片？

保存图片是可以的，你的意思是，每次获取到一张新的图片，就把图片保存到指定目录？
至于风险，倒是没有，api本身就是给你用的，除非api自己有限制，比如一天获取多少次这样。这个可以加个开关，多个页面共用背景是可以的。（这个仅限于json返回的api）

**Comment by xh321** [comment]
> 更新试了下，可以了! 另外还想说一个，是否可以提供一个选项，可以保存从Api获取的图片到指定目录？
> 
> 最后还有一个问题，就是每次打开新的界面(例如查看图片的界面)背景图也会加载一个新的， 如果是使用本地图片倒也不是什么大问题，如果过于频繁地使用API的会不会有其他的风险? 有没有风险我不是很了解啦，是否需要多加一个限制，使用API时让多个界面共用当前的背景图片？

第二个已经在最新版有选项了，可以让所有窗体共用一张背景图

**Comment by AkatsukiZhang** [comment]
> 保存图片是可以的，你的意思是，每次获取到一张新的图片，就把图片保存到指定目录？ 至于风险，倒是没有，api本身就是给你用的，除非api自己有限制，比如一天获取多少次这样。这个可以加个开关，多个页面共用背景是可以的。（这个仅限于json返回的api）

图片如何保存，在插件设置里没有看到相关的，我也不知道到如何保存，能在插件设置里体现出来就好了。
至于保存目录的话，能指定文件夹肯定更好啦!

保存图片的话如果能在侧边栏增加一个按钮，或者在聊天界面的右键菜单里添加选项的话，应该也不错?

**Comment by xh321** [comment]
> > 保存图片是可以的，你的意思是，每次获取到一张新的图片，就把图片保存到指定目录？ 至于风险，倒是没有，api本身就是给你用的，除非api自己有限制，比如一天获取多少次这样。这个可以加个开关，多个页面共用背景是可以的。（这个仅限于json返回的api）
> 
> 图片如何保存，在插件设置里没有看到相关的，我也不知道到如何保存，能在插件设置里体现出来就好了。 至于保存目录的话，能指定文件夹肯定更好啦!
> 
> 保存图片的话如果能在侧边栏增加一个按钮，~或者在聊天界面的右键菜单里添加选项的话，~应该也不错? (发现聊天界面右键空白位置没有右键菜单了，哎？)

可以在主界面左下方，qq自己菜单的上面，加一个保存当前背景图的按钮，但总之保存还没做，请等待啦

**Comment by xh321** [comment]
最新版已经全部支持，你可以试试了

**Comment by AkatsukiZhang** [comment]
更新试了下，行了！
另外补充一下
1) 从插件商店更新插件后重启没有出现保存的按钮，重置插件默认设置后重启才出现按钮。
2) 在设置修改保存路径的时候，设置界面没有更新显示新的路径(实际上已经修改了，界面没有刷新，重开设置界面才能看到新路径)
3) api有<del>极小的</del>概率会请求到同一张图片，在tmp文件夹里的缓存能否保留链接的原始文件名，然后排除一下重复缓存的问题？
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/22972499/b2cab2e8-6736-4774-9873-572076667601)

**Comment by xh321** [comment]
> 2\. 上已经修改

好的，收到，会修复的。至于第三点，可以

**Comment by AkatsukiZhang** [comment]
再问一下，背景更新间隔最长是只能999秒吗？
发现我输入的3600秒改了没生效，
实际运行的间隔是默认的600秒
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/22972499/0818c4e1-00a0-4d77-b298-04c8e2f4409d)
输入框上点了下[减]从3600->999秒了
![GIF](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/22972499/f4caddf7-c7e6-456e-90c1-131787f9c45d)

**Comment by xh321** [comment]
> 再问一下，背景更新间隔最长是只能999秒吗？ 发现我输入的3600秒改了没生效， 实际运行的间隔是默认的600秒 ![image](https://private-user-images.githubusercontent.com/22972499/302955727-0818c4e1-00a0-4d77-b298-04c8e2f4409d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDY4NzgsIm5iZiI6MTcwNzMwNjU3OCwicGF0aCI6Ii8yMjk3MjQ5OS8zMDI5NTU3MjctMDgxOGM0ZTEtMDBhMC00ZDc3LWIyOTgtMDRjOGUyZjQ0MDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDExNDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYzIyODdkYzM5NDg0Zjk2ZGUyY2NhYWI5MTI0ODJmZTFkMTk5NDhhNTk4ZDNhYmNlMDhhYzNjNjUyNDI3MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m9pa1ONvTq4qjNES3rbxYXCI2Lu4MBsD9_lrxLzEidU) 输入框上点了下[减]从3600->999秒了 ![GIF](https://private-user-images.githubusercontent.com/22972499/302956582-f4caddf7-c7e6-456e-90c1-131787f9c45d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDY4NzgsIm5iZiI6MTcwNzMwNjU3OCwicGF0aCI6Ii8yMjk3MjQ5OS8zMDI5NTY1ODItZjRjYWRkZjctYzdlNi00NTZlLTkwYzEtMTMxNzg3ZjljNDVkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDExNDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZjY4MGQyYzgzZDgwOGQ2N2RiZTYzYzI4MmM3ZGZiZWYyNDYwMTA2ODk4M2E0ZWY4MGJhYTc3MzVjOTg4MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gtTngKmrrmt4dfZgNUiIVepQpUNMdXPTIHJ4P1MP7O4) [ ![GIF](https://private-user-images.githubusercontent.com/22972499/302956582-f4caddf7-c7e6-456e-90c1-131787f9c45d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDY4NzgsIm5iZiI6MTcwNzMwNjU3OCwicGF0aCI6Ii8yMjk3MjQ5OS8zMDI5NTY1ODItZjRjYWRkZjctYzdlNi00NTZlLTkwYzEtMTMxNzg3ZjljNDVkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDExNDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZjY4MGQyYzgzZDgwOGQ2N2RiZTYzYzI4MmM3ZGZiZWYyNDYwMTA2ODk4M2E0ZWY4MGJhYTc3MzVjOTg4MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gtTngKmrrmt4dfZgNUiIVepQpUNMdXPTIHJ4P1MP7O4) ](https://private-user-images.githubusercontent.com/22972499/302956582-f4caddf7-c7e6-456e-90c1-131787f9c45d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDY4NzgsIm5iZiI6MTcwNzMwNjU3OCwicGF0aCI6Ii8yMjk3MjQ5OS8zMDI5NTY1ODItZjRjYWRkZjctYzdlNi00NTZlLTkwYzEtMTMxNzg3ZjljNDVkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDExNDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZjY4MGQyYzgzZDgwOGQ2N2RiZTYzYzI4MmM3ZGZiZWYyNDYwMTA2ODk4M2E0ZWY4MGJhYTc3MzVjOTg4MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gtTngKmrrmt4dfZgNUiIVepQpUNMdXPTIHJ4P1MP7O4) [ ](https://private-user-images.githubusercontent.com/22972499/302956582-f4caddf7-c7e6-456e-90c1-131787f9c45d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDY4NzgsIm5iZiI6MTcwNzMwNjU3OCwicGF0aCI6Ii8yMjk3MjQ5OS8zMDI5NTY1ODItZjRjYWRkZjctYzdlNi00NTZlLTkwYzEtMTMxNzg3ZjljNDVkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDExNDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZjY4MGQyYzgzZDgwOGQ2N2RiZTYzYzI4MmM3ZGZiZWYyNDYwMTA2ODk4M2E0ZWY4MGJhYTc3MzVjOTg4MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gtTngKmrrmt4dfZgNUiIVepQpUNMdXPTIHJ4P1MP7O4)

确实是，这是输入框长度问题，我可以加长一点

**Comment by xh321** [comment]
最新版已支持，等下可以更新试试

**Comment by xh321** [comment]
尝试进行了一些修复，但不一定有效果，看看吧

**Comment by xh321** [comment]
如果已经解决问题了我先关闭issue了
