### ISSUE TITLE
“已解决” 背景插件配置页面空白

### ISSUE THREAD

**Issue by LanYanGy1103** [xh321/LiteLoaderQQNT-Background-Plugin#31]
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/39426140/c4e15857-fbbf-485d-b490-6f80f276445c)
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/39426140/8e8643ad-b39f-4401-be35-d4cf08ae94c0)

背景插件配置页面空白，但是我放了一张图片在文档说的路径文件夹内被加载了，如图，但是只是在这个页面加载，聊天页面没加载。
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/39426140/501610e1-c46e-4acc-8a34-09a85ff68d20)
config.json配置文件如上

**Comment by LanYanGy1103** [comment]
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/39426140/7e27b173-0180-4a5e-9755-43dfe4d92adb)

**Comment by LEAVE114514** [comment]
我这只有这一个插件也会无法显示页面，其他插件全部删除，没效果

**Comment by LanYanGy1103** [comment]
已解决，添加tmp文件夹后重启生效

**Comment by xh321** [comment]
okok明白问题了，下个版本修复
