### ISSUE TITLE
关于和#31一样的页面空白问题

### ISSUE THREAD

**Issue by LEAVE114514** [xh321/LiteLoaderQQNT-Background-Plugin#32]
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/158803897/f086b849-f342-418a-82c1-94b868f8d8e3)
我把所有的可能冲突插件都删除掉了，重启数次都还是无法显示页面，请问这如何解决呢？

**Comment by xh321** [comment]
我现在更新一个版本你再试试

**Comment by LEAVE114514** [comment]
搞定，最新版本问题已修复

**Comment by LEAVE114514** [comment]
话说最新版本已经不支持视频背景了吗？

**Comment by xh321** [comment]
> 话说最新版本已经不支持视频背景了吗？

一直支持呀，什么问题？

**Comment by LEAVE114514** [comment]
可能是我的操作问题。。。。刚开始无法读取到视频
