### ISSUE TITLE
关于视频背景问题

### ISSUE THREAD

**Issue by LEAVE114514** [xh321/LiteLoaderQQNT-Background-Plugin#33]
之前的版本支持视频背景，但是播放完成后会卡死，当时我就想到了一个解决方法让视频持续播放
我新建另一个文件夹，文件夹里放两个以上同一文件但是不同名字，在背景卡死前轮换壁纸以让视频壁纸延续，这个方法可以让4k视频持续播放，是否可以改进一下？

**Comment by xh321** [comment]
会卡死是什么问题，能否发一下视频给我看看？我本地测试视频能正常循环播放

**Comment by xh321** [comment]
可能还和视频编码有关，我测试的视频是H.264编码，H.265编码视频似乎无法播放

**Comment by xh321** [comment]
https://lf3-cdn-tos.bytegoofy.com/obj/tcs-client/resources/video_demo_hevc.html
这里测试的视频大部分都可以正常播放

**Comment by LEAVE114514** [comment]
反馈，是不是视频分辨率的问题？我的视频是3840×2160的分辨率，播放到不知道啥时候突然就变回默认

**Comment by LEAVE114514** [comment]
我刚进厕所看到消息出来一看果然卡死（

**Comment by LEAVE114514** [comment]
刷新视频播放后恢复

**Comment by xh321** [comment]
我下载里面的8K视频都正常播放的

**Comment by xh321** [comment]
你也可以下载里面的视频播放试试看会不会卡死，看看是视频的问题还是你那边其他的问题

**Comment by LEAVE114514** [comment]
有时候点开聊天记录，也会变回默认背景，几率比较小？

**Comment by xh321** [comment]
这种和代码关系不大，应该还是Electron对视频格式的兼容性问题。你QQ版本多少

**Comment by LEAVE114514** [comment]
版本是9.9.7

**Comment by LEAVE114514** [comment]
最新版我怕patch过不了就没更新

**Comment by xh321** [comment]
> 版本是9.9.7

我这里也是9.9.7，理应都一样的，大概就是你视频的问题

**Comment by LEAVE114514** [comment]
又卡掉了这次，我把视频链接发给你吧，小红车的https://steamcommunity.com/sharedfiles/filedetails/?id=2974118619

**Comment by xh321** [comment]
经过测试，正常播放，也不会卡死，你看看你内存或者显存是不是炸了

**Comment by LEAVE114514** [comment]
可能是显存炸了，桌面和QQ一起吃显存，8G可能有点吃不消

**Comment by LEAVE114514** [comment]
显存占用最高占用率到了80%

**Comment by xh321** [comment]
这个可能没什么办法了，是electron需要优化的问题。你是否开启了多个窗口？每个窗口都会单独占用显存播放视频。

**Comment by xh321** [comment]
先关闭issue了，如果有问题可以reopen

**Comment by LEAVE114514** [comment]
我尝试了重启之后只打开QQ，wallpaper也关闭，还是卡死，有不卡死的时候的话，一对QQ做出切换界面等操作就有几率会卡死
