### ISSUE TITLE
媒体播放器也被套上了背景

### ISSUE THREAD

**Issue by tennshishiji** [xh321/LiteLoaderQQNT-Background-Plugin#34]
从0.x版本LL过来的，现在新版本查看图片的时候背景也是我设置的背景，好像没有发现能让媒体播放器变成qq默认的样式的办法（“是否对所有窗口共用背景”）没有效果 拜托大大能不能加一下有关的功能

**Comment by tennshishiji** [comment]
![QQ_fiKSxGD6hB](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/159172944/c4d1bc16-c6d5-4bd5-bc27-a5408460a609)
例

**Comment by xh321** [comment]
ok，可以加配置开关

**Comment by xh321** [comment]
最新版已支持自定义开关
