### ISSUE TITLE
隐藏位于侧边栏下方的更新背景和保存网络图片背景按钮

### ISSUE THREAD

**Issue by 1625423178** [xh321/LiteLoaderQQNT-Background-Plugin#35]
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/115442729/41d67b20-427a-4e1e-8dbc-24176b199e6e)

（希望可以在背景插件设置提供一个开关，用于显示和隐藏这两个按钮）
（对单背景图来说使用率过低，追求简洁（）
此致

**Comment by xh321** [comment]
好的

**Comment by xh321** [comment]
最新版会根据具体情况来显示，比如如果是文件夹或API，才显示切换图片按钮；如果是网络图片，才显示图片保存按钮

**Comment by xh321** [comment]
如果符合需求我先关闭issue，如果还有其他情况可以reopen。
