### ISSUE TITLE
[Bug] 消息列表顶部的搜索框过于不明显

### ISSUE THREAD

**Issue by MRUIAW** [xh321/LiteLoaderQQNT-Background-Plugin#36]
搜索框展开后过于不明显(尤其是搜索时)
[原因]: 与 MSpring Theme主题 同时启用时会有这种情况

这是未启用插件的效果:
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/119018519/c312b10f-209d-46f1-8d9d-71083027e512)

启用插件后的效果:
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/119018519/a7e0caff-6cd6-4cfe-81b6-d36caa2d2e85)
(好吧打码了可能看不出区别, 第二张不打码了)

**Comment by xh321** [comment]
好，晚些我看看

**Comment by xh321** [comment]
去背景插件设置里把毛玻璃特效关了就好，然后我会更新一版，降低背景透明度，会好很多

**Comment by yhzcake** [comment]
搜索的这个窗口提取图片主色调加个底色就好了

**Comment by xh321** [comment]
> 搜索的这个窗口提取图片主色调加个底色就好了

这个是和mspring插件冲突的问题，和底色关系不大

**Comment by xh321** [comment]
如果已经解决问题了我先关闭issue，有问题可以reopen。
