### ISSUE TITLE
[feat]希望能根据白天夜间设置不同的壁纸

### ISSUE THREAD

**Issue by yhzcake** [xh321/LiteLoaderQQNT-Background-Plugin#37]
如题,我桌面壁纸是两张分别是白天和夜间主题,想跟桌面壁纸保持一致
还有,可不可以加一个无背景图也有一个带主题背景色的毛玻璃模糊效果?
另:mspring theme的背景颜色透明度也会影响这个插件,用的时候直接把那个设置全透明就好了

**Comment by xh321** [comment]
你的想法我也考虑到了，会在后期添加
无背景图已经支持了，图片来源选择无就行

**Comment by yhzcake** [comment]
我的意思是无背景图的时候也有透明，就是能看到后面那种，能弄吗

**Comment by xh321** [comment]
> 我的意思是无背景图的时候也有透明，就是能看到后面那种，能弄吗

现在选择无背景图后你可以进设置把不透明度拉最低
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/37585529/b84c5bf7-ce82-40ea-99c5-ad0aa569da52)
可以发现还是有高斯模糊
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/37585529/3a2db427-61fc-43af-9e00-d59e6a3edd9e)
这是QQ自带的窗体效果，从渲染层似乎无法解决。

**Comment by yhzcake** [comment]
我就不新开issue了
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/80627671/e2b5da56-f0dc-45d0-81eb-242d2863640f)

新版liteloader里会改变插件列表开关的样式,看不清

**Comment by yhzcake** [comment]
> 新版liteloader里会改变插件列表开关的样式,看不清

将render.js中的两个setting-switch删掉就好了

**Comment by yhzcake** [comment]
所以什么时候上线根据白天夜间切不同壁纸啊(((

**Comment by xh321** [comment]
最近太忙了，不知道什么时候能继续更新，需要等我空出时间再搞

**Comment by yhzcake** [comment]
好的好的,我是想直接用media判断主题直接换两张图就好了,感觉挺简单的

**Comment by xh321** [comment]
> 好的好的,我是想直接用media判断主题直接换两张图就好了,感觉挺简单的

是，但是还需要设置界面去适配，主要是这个麻烦

**Comment by yhzcake** [comment]
自己写css加载了..这个插件应该弃更了吧

**Comment by xh321** [comment]
也不能说弃更，只是更新周期很长（

**Comment by yhzcake** [comment]
半年没更新标个半弃坑（
