### ISSUE TITLE
网络图片缓存问题

### ISSUE THREAD

**Issue by 888pppj** [xh321/LiteLoaderQQNT-Background-Plugin#39]
是否可以增加一个选项来关闭这个自动缓存呢？
![Uploading QQ截图20240215151012.png…]()
我不知道如何发图片，我指的的网络图片自动缓存到文件夹，是否可以关闭
qwq

**Comment by xh321** [comment]
明白你的意思了，你想关闭缓存的原因主要是怕什么呢？因为要多个窗体共用一张图的话就得保存这张图下来才行
如果是怕大小过大的话，1.你可以手动清理2.我可以加总数/总大小限制

**Comment by 888pppj** [comment]
> 明白你的意思了，你想关闭缓存的原因主要是怕什么呢？因为要多个窗体共用一张图的话就得保存这张图下来才行 如果是怕大小过大的话，1.你可以手动清理2.我可以加总数/总大小限制

感谢回复！手动清理就可以了

**Comment by xh321** [comment]
以后我会加一个总大小限制的配置选项，到了限制自动清理。
