### ISSUE TITLE
[Bug]清空网络图片缓存文件夹后，有可能会拉取超过1张的图片。

### ISSUE THREAD

**Issue by AkatsukiZhang** [xh321/LiteLoaderQQNT-Background-Plugin#41]
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/22972499/4ae398fe-063f-4bcb-9382-a0265b52406d)
如图，点了下清空缓存，文件夹噌噌噌从0生出了30个文件。
<details>
  <summary>展开设置截图</summary>

![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/22972499/628316ae-0c8d-4e85-8f5e-dac894e9347f)

  </details>
使用的API链接是(https://api.lolicon.app/setu/v2)，获得的是Pixiv的原始图片链接，有可能因为网络问题下载失败(增加一个0kb的文件)，
不知道跟这个有没有关系，我姑且提一下。

**Comment by xh321** [comment]
ok，我会排查的

**Comment by AkatsukiZhang** [comment]
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/22972499/4ee6d75d-7dc7-471c-8b08-d37625bf2af7)
貌似清空缓存后下载的第一张图失败了，触发这个bug的概率大点?之前截图的30张的第一张也是下载失败的。
另外还有一个问题就是，挂机一整天，CPU占用会变高(30%左右)，清空缓存后CPU占用就正常(5%以下)。
不知道是不是这个插件的问题？

**Comment by AkatsukiZhang** [comment]
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/22972499/b478289b-d084-4e91-9938-1a9d291e00d2)
又试了下，好像跟下载失败关系又不大了,这次触发了，但是没有失败的文件。

**Comment by xh321** [comment]
> ![image](https://private-user-images.githubusercontent.com/22972499/307464857-4ee6d75d-7dc7-471c-8b08-d37625bf2af7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzIwNjcsIm5iZiI6MTcwODc3MTc2NywicGF0aCI6Ii8yMjk3MjQ5OS8zMDc0NjQ4NTctNGVlNmQ3NWQtN2RjNy00NzFjLThiMDgtZDM3NjI1YmYyYWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDEwNDkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYWYzZTU1ZTI0ZGFhYmJjNzQzNDNjMTE4ODZlYmMzOGRkZjgzZmZlNmEyODIxY2U1YzNlMTFhMDAxNDcxZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.81369eaut5lCUiHDwhWt99pP9auk6QuGhveSnb7NJOs) 貌似清空缓存后下载的第一张图失败了，触发这个bug的概率大点?之前截图的30张的第一张也是下载失败的。 另外还有一个问题就是，挂机一整天，CPU占用会变高(30%左右)，清空缓存后CPU占用就正常(5%以下)。 不知道是不是这个插件的问题？

CPU占用变高我倒是没发现过，我一直开着背景插件CPU占用也就5%左右。建议你关闭背景插件再挂机一天试试看，如果还是高就不是背景插件的问题。
缓存与CPU占用应该无关，缓存下载之后，更换下一张图片后，之前的缓存都不会去动了。而且你缓存文件夹里就几张图片，怎么想也不应该有关联。

**Comment by xh321** [comment]
另外有些图片下载错误可能是因为图片被删了或者被和谐了
你可以看那些1kb的文件里面内容
我这边显示是
```
<!DOCTYPE html>
<html>
    <h1>404 Not Found</h1>
</html>
```
这也是常有的事

**Comment by AkatsukiZhang** [comment]
> 另外有些图片下载错误可能是因为图片被删了或者被和谐了 你可以看那些1kb的文件里面内容 我这边显示是
> 
> ```
> <!DOCTYPE html>
> <html>
>     <h1>404 Not Found</h1>
> </html>
> ```
> 
> 这也是常有的事

![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/22972499/b8a572bd-341f-4752-947e-92e6fa609395)

![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/22972499/c381c2b5-3108-4565-980c-13cec2529eae)
用图片ID去查了下，发现不完全是 图片删除或和谐 之类的情况，可能是API返回了错误的(或旧的)原始链接吧，问题不大，
现在的问题是清空缓存会多拉好几次图片，刚刚我试了又拉了25张图。

**Comment by xh321** [comment]
> > 另外有些图片下载错误可能是因为图片被删了或者被和谐了 你可以看那些1kb的文件里面内容 我这边显示是
> > ```
> > <!DOCTYPE html>
> > <html>
> >     <h1>404 Not Found</h1>
> > </html>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这也是常有的事
> 
> ![image](https://private-user-images.githubusercontent.com/22972499/307515504-b8a572bd-341f-4752-947e-92e6fa609395.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzM1MTUsIm5iZiI6MTcwODc3MzIxNSwicGF0aCI6Ii8yMjk3MjQ5OS8zMDc1MTU1MDQtYjhhNTcyYmQtMzQxZi00NzUyLTk0N2UtOTJlNmZhNjA5Mzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDExMTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NTQyYTQyNjZmMzI1YTA3ZWJjMGFhMGJkMjBiMDZjMDk0MTBkZTFkOThlNjg1ZmM3ODNhYjU5ODU0YmEzZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Nfan2sFPSB8xR_e12Sza6EcRh-Z7gKZ4321znSsJ8M)
> 
> ![image](https://private-user-images.githubusercontent.com/22972499/307515434-c381c2b5-3108-4565-980c-13cec2529eae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzM1MTUsIm5iZiI6MTcwODc3MzIxNSwicGF0aCI6Ii8yMjk3MjQ5OS8zMDc1MTU0MzQtYzM4MWMyYjUtMzEwOC00NTY1LTk4MGMtMTNjZWMyNTI5ZWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDExMTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZTc3MzdiMjBmMWRmMzVjYTBhOTUyMjY4NzRlYzg2OTRjZWFhODdlYmZhN2JiNjdlM2I3ZWRhNjlmNzE4NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hfD0qDKVp05dLrezGFMyObEN2HIU5NIQy8m6FJNx-lM) 用图片ID去查了下，发现不完全是 图片删除或和谐 之类的情况，可能是API返回了错误的(或旧的)原始链接吧，问题不大， 现在的问题是清空缓存会多拉好几次图片，刚刚我试了又拉了25张图。

API返回404但是原图存在也是正常情况，这是API的问题。下一个版本我会增加检测，如果访问不到，就自动换下一张图。至于你说一次性拉很多张，你是不是手动点击轮换图片了呀，或者你轮换间隔很短。图片下载需要时间，上一张没下完你又点更换下载下一张，这就导致，只变了一次，但实际上下了2张图

**Comment by xh321** [comment]
方便留个联系方式吗（等下删）免得一直issue低效交流（

**Comment by AkatsukiZhang** [comment]
> > ![image](https://private-user-images.githubusercontent.com/22972499/307464857-4ee6d75d-7dc7-471c-8b08-d37625bf2af7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzIwNjcsIm5iZiI6MTcwODc3MTc2NywicGF0aCI6Ii8yMjk3MjQ5OS8zMDc0NjQ4NTctNGVlNmQ3NWQtN2RjNy00NzFjLThiMDgtZDM3NjI1YmYyYWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDEwNDkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYWYzZTU1ZTI0ZGFhYmJjNzQzNDNjMTE4ODZlYmMzOGRkZjgzZmZlNmEyODIxY2U1YzNlMTFhMDAxNDcxZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.81369eaut5lCUiHDwhWt99pP9auk6QuGhveSnb7NJOs) 貌似清空缓存后下载的第一张图失败了，触发这个bug的概率大点?之前截图的30张的第一张也是下载失败的。 另外还有一个问题就是，挂机一整天，CPU占用会变高(30%左右)，清空缓存后CPU占用就正常(5%以下)。 不知道是不是这个插件的问题？
> 
> CPU占用变高我倒是没发现过，我一直开着背景插件CPU占用也就5%左右。建议你关闭背景插件再挂机一天试试看，如果还是高就不是背景插件的问题。 缓存与CPU占用应该无关，缓存下载之后，更换下一张图片后，之前的缓存都不会去动了。而且你缓存文件夹里就几张图片，怎么想也不应该有关联。

这个我确实得再试一试。
你可以加一下(154025280 测试用群)

**Comment by AkatsukiZhang** [comment]
> > > 另外有些图片下载错误可能是因为图片被删了或者被和谐了 你可以看那些1kb的文件里面内容 我这边显示是
> > > ```
> > > <!DOCTYPE html>
> > > <html>
> > >     <h1>404 Not Found</h1>
> > > </html>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这也是常有的事
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/22972499/307515504-b8a572bd-341f-4752-947e-92e6fa609395.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzM1MTUsIm5iZiI6MTcwODc3MzIxNSwicGF0aCI6Ii8yMjk3MjQ5OS8zMDc1MTU1MDQtYjhhNTcyYmQtMzQxZi00NzUyLTk0N2UtOTJlNmZhNjA5Mzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDExMTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NTQyYTQyNjZmMzI1YTA3ZWJjMGFhMGJkMjBiMDZjMDk0MTBkZTFkOThlNjg1ZmM3ODNhYjU5ODU0YmEzZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Nfan2sFPSB8xR_e12Sza6EcRh-Z7gKZ4321znSsJ8M)
> > ![image](https://private-user-images.githubusercontent.com/22972499/307515434-c381c2b5-3108-4565-980c-13cec2529eae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzM1MTUsIm5iZiI6MTcwODc3MzIxNSwicGF0aCI6Ii8yMjk3MjQ5OS8zMDc1MTU0MzQtYzM4MWMyYjUtMzEwOC00NTY1LTk4MGMtMTNjZWMyNTI5ZWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDExMTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZTc3MzdiMjBmMWRmMzVjYTBhOTUyMjY4NzRlYzg2OTRjZWFhODdlYmZhN2JiNjdlM2I3ZWRhNjlmNzE4NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hfD0qDKVp05dLrezGFMyObEN2HIU5NIQy8m6FJNx-lM) 用图片ID去查了下，发现不完全是 图片删除或和谐 之类的情况，可能是API返回了错误的(或旧的)原始链接吧，问题不大， 现在的问题是清空缓存会多拉好几次图片，刚刚我试了又拉了25张图。
> 
> API返回404但是原图存在也是正常情况，这是API的问题。下一个版本我会增加检测，如果访问不到，就自动换下一张图。至于你说一次性拉很多张，你是不是手动点击轮换图片了呀，或者你轮换间隔很短。图片下载需要时间，上一张没下完你又点更换下载下一张，这就导致，只变了一次，但实际上下了2张图

我只点了清空缓存文件夹，没有其他的操作了，设置的轮换时间是3600s.
