### ISSUE TITLE
bug，背景视频会卡死

### ISSUE THREAD

**Issue by lovelymeng** [xh321/LiteLoaderQQNT-Background-Plugin#43]
背景视频会卡死只有自动轮换的会卡死，猜测原因应该是视频放完导致的卡死

**Comment by lovelymeng** [comment]
之前没有视频版本，视频转gif格式无问题，延迟60秒，现在有视频版本不管什么格式自动轮换后卡死，延迟280秒，（视频长度4分50秒）就算都是视频长度8秒不超过20秒，一会也会卡死。

**Comment by xh321** [comment]
只有视频类型会卡死对吧
能否视频发我，同时把配置界面截个图，我这边复现一下

**Comment by lovelymeng** [comment]
你随便啥视频都行，唯一一点是背景更新间隔得大于视频时间




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月1日(星期五) 凌晨0:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xh321/LiteLoaderQQNT-Background-Plugin] bug，背景视频会卡死 (Issue #43)





 
只有视频类型会卡死对吧
 能否视频发我，同时把配置界面截个图，我这边复现一下

**Comment by lovelymeng** [comment]
长时间手动轮换也会卡

**Comment by lovelymeng** [comment]
Uploading QQ202431-05751.mp4…

**Comment by lovelymeng** [comment]
Uploading QQ202431-05751.mp4…

**Comment by xh321** [comment]
同时观察一下你的内存和显存是否有占满的情况

**Comment by lovelymeng** [comment]
轻量工具箱的视频背景功能跟此背景视频插件不是同一层，轻量工具箱的视频背景切换是秒切，目前没有卡死。

**Comment by lovelymeng** [comment]
https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/75792002/06f1166b-73db-417e-9b27-7764fd02d60e

**Comment by lovelymeng** [comment]
https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/75792002/3c084a3c-e2be-4252-8d31-83bc1a9a6873

**Comment by xh321** [comment]
> 轻量工具箱的视频背景功能跟此背景视频插件不是同一层，轻量工具箱的视频背景切换是秒切，目前没有卡死。

有一说一是同一层，除非你没更新最新版

**Comment by xh321** [comment]
再看了一遍代码，发现有问题，发布了新版本，你更新试试看

**Comment by lovelymeng** [comment]
没问题了
