### ISSUE TITLE
是否可增加覆盖侧边栏功能

### ISSUE THREAD

**Issue by liutao86** [xh321/LiteLoaderQQNT-Background-Plugin#44]
能否添加一个覆盖侧边栏功能，如图左侧可显示背景图
![{D9836FCA-5AE8-4cc8-AFBA-030BBBEE2151}](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/111474097/27a20c70-0394-4622-8e88-b7eaeb2c43f9)

**Comment by liutao86** [comment]
这是我用插件“轻量工具箱”的“背景调整”改的，但是轻量工具箱的换背景图功能没这个插件完善

**Comment by xh321** [comment]
侧边栏其实也有覆盖，只是透明度调得比较低，我可以调高一点，请等待下个版本

**Comment by liutao86** [comment]
> 侧边栏其实也有覆盖，只是透明度调得比较低，我可以调高一点，请等待下个版本

thank you sir

**Comment by xh321** [comment]
最新版已调整，可以看看是否满足

**Comment by AkatsukiZhang** [comment]
> 最新版已调整，可以看看是否满足

搜索栏的透明度是否可以一并调整下(夜间模式下很明显黑的一块x

**Comment by xh321** [comment]
最新版已调整，可以看看

**Comment by liutao86** [comment]
> 最新版已调整，可以看看
非常好优化，感谢感谢
