### ISSUE TITLE
[Bug] 群助手二级页标题透明度异常

### ISSUE THREAD

**Issue by ChenXiii-1002** [xh321/LiteLoaderQQNT-Background-Plugin#46]
# 需求
调整群助手二级页标题透明度与其他一致。
类似的 issue #44 https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/issues/44#issuecomment-1987731992

## Version
QQNT v9.9.7-21453 x64
LiteLoaderQQNT [v1.0.3](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/releases/tag/1.0.3)
Background-Plugin [v0.2.16](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/releases/tag/0.2.16)

## Screenshot
（深色模式）
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/115442729/769bb337-5077-47c2-9ad6-48981034e48e)

（浅色模式）
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/115442729/b6ee3881-9747-4aba-b28c-bf543b5e2600)

**Comment by xh321** [comment]
明白，下个版本修改

**Comment by xh321** [comment]
最新版已修复
