### ISSUE TITLE
无法使用网络图片背景

### ISSUE THREAD

**Issue by Moshimoxi** [xh321/LiteLoaderQQNT-Background-Plugin#47]
插件版本0.2.17
LiteLoader版本1.0.3
本地图片背景可以正常使用，但是无法使用API背景，获取到的图片都是不可读取状态
![屏幕截图 2024-03-15 230929](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/89623860/936427f1-a333-40f1-9a4d-e7f5a777797c)
API地址如下 https://t.mwm.moe/ysz

**Comment by xh321** [comment]
是已经解决了还是？

**Comment by Moshimoxi** [comment]
我重新试了一下api接口，发现这个接口之前可以用旧版本liteloarder加旧版本背景模块获取，也可以用Chrome浏览器直接获取图片，但是不能用新版模块(我试了0.2.25以后的版本)获取，我看其他api站点收录的这个接口也不能在页面显示，不知道是不是有什么特殊规则，现在换了一个api可以正常用了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月24日 01:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [xh321/LiteLoaderQQNT-Background-Plugin] 无法使用网络图片背景 (Issue #47) |

是已经解决了还是？

**Comment by Moshimoxi** [comment]
说错了，是0.2.5之后的版本

**Comment by xh321** [comment]
找到罪魁祸首了
这个api返回的图片包含一些php报错内容
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/37585529/9760ccbd-6f4d-4bb7-aa89-036d3c860cac)
导致图片解析失败

**Comment by xh321** [comment]
为什么浏览器可以访问，因为浏览器带了UA，我这里没带，所以他报警告了

**Comment by xh321** [comment]
其他不能用的api也可以列一下，我一个个测试

**Comment by xh321** [comment]
之前为啥可以，因为旧版本是前端获取，新版本是后端统一获取，有点不太一样的

**Comment by Moshimoxi** [comment]
> 其他不能用的api也可以列一下，我一个个测试

我找的几个api就这一个不能用，其他的都正常😂

**Comment by Moshimoxi** [comment]
> 为什么浏览器可以访问，因为浏览器带了UA，我这里没带，所以他报警告了

原来如此，我说咋突然不行了，解答了我的疑惑

**Comment by xh321** [comment]
已更新一个版本，你可以试试刚刚那个API，我本地测试已经OK了
