### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by nogodnodevil** [xh321/LiteLoaderQQNT-Background-Plugin#53]
大佬，像图片中圈出来的用户名，时间，群公告等等字体的颜色修改的相关配置代码在哪，能指个路吗
![PixPin_2024-04-11_15-25-49](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/151034627/c044a69d-4740-43b6-810b-d740f01d1e5c)

**Comment by xh321** [comment]
可装Chii-Devtools后F12查看
我帮你看了一下，class是text-normal、text-ellipsis，但是群公告没有特别的class，只有容器有content这个class

**Comment by nogodnodevil** [comment]
> 可装Chii-Devtools后F12查看 我帮你看了一下，class是text-normal、text-ellipsis，但是群公告没有特别的class，只有容器有content这个class

感谢大佬，我研究研究
