### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by LLolloLLolo** [xh321/LiteLoaderQQNT-Background-Plugin#58]
![屏幕截图 2024-05-12 105013](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/110021808/79632a5e-c60f-4865-b50c-807587746414)
排查过兼性问题 与兼容性无关

**Comment by xh321** [comment]
你安装插件方式有误，没有带上依赖。
如果你是clone的插件repo，请自行进行npm i依赖安装。
建议直接从release下载完整包。
