### ISSUE TITLE
字体颜色在代码的哪里呢？

### ISSUE THREAD

**Issue by hugo-Miles** [xh321/LiteLoaderQQNT-Background-Plugin#6]
我想修改下自己发出的字体颜色，但找不着代码😂

**Comment by xh321** [comment]
CSS样式类为 .message-container--self .text-normal
例如
.message-container--self .text-normal {
    color:grey;
}
我再写个附加CSS的插件吧，不然还挺麻烦的

**Comment by xh321** [comment]
[Custom-CSS](https://github.com/xh321/LiteLoaderQQNT-Custom-CSS)
写好了，这个自带的style.css就能符合你的需求，你可以自行修改
