### ISSUE TITLE
调整主背景图覆盖层透明度不生效，  背景更新间隔无法输入数字

### ISSUE THREAD

**Issue by xiureal** [xh321/LiteLoaderQQNT-Background-Plugin#61]
调整主背景图覆盖层透明度不生效，  背景更新间隔无法输入数字

**Comment by xh321** [comment]
请带上你的QQ版本号，并建议降级9.9.7。新版本并不一定兼容，暂时没空做兼容，很抱歉

**Comment by xiureal** [comment]
> 请带上你的QQ版本号，并建议降级9.9.7。 新版本并不一定兼容，暂时没空做兼容，很抱歉

上一个版本还能正常用，调整主背景图覆盖层透明度正常，  背景更新间隔无法输入数字在重启QQ刷新缓存正常用了

**Comment by xh321** [comment]
所以最终可以正常用了对嘛

**Comment by xiureal** [comment]
> 所以最终可以正常用了对嘛
对的
