### ISSUE TITLE
QQNT 9.9.11-24616已失效

### ISSUE THREAD

**Issue by Clackz** [xh321/LiteLoaderQQNT-Background-Plugin#62]
![图片](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/42225208/41b707eb-9238-4123-94da-c22ace84a289)
如图所示，升级到最新版本后背景功能在主界面失效了

**Comment by xh321** [comment]
正如readme中所说，新版本尚未适配，我目前没空做，非常抱歉，建议降级使用

**Comment by Clackz** [comment]
9.9.11-24815版本已恢复正常
