### ISSUE TITLE
#BUG主窗口界面不显示背景

### ISSUE THREAD

**Issue by lovelymeng** [xh321/LiteLoaderQQNT-Background-Plugin#65]
![QQ_1721106535296](https://github.com/user-attachments/assets/eaa56a87-1b7a-4c6a-886d-e76b1889b533)

**Comment by Artificialheaven** [comment]
我的新版本QQ也不能显示主界面背景图片了

**Comment by Artificialheaven** [comment]
> 其他界面还能显示，只有聊天界面没有

是这样，老版本QQ好像没有这个问题

**Comment by minecraft4668** [comment]
同问

**Comment by xh321** [comment]
看README，新版本尚未适配，很抱歉，没时间更新，建议降级9.9.7

**Comment by mingyu0401** [comment]
> 我的新版本QQ也不能显示主界面背景图片了

@lovelymeng 实测退回到9.9.12-25493或者以下(应该)就会显示了.退回会吧,运行下安装的,再装下llqqnt(我用的一键项目).各版本可以在手机上Appshare应用找到.

**Comment by AkatsukiZhang** [comment]
> > 我的新版本QQ也不能显示主界面背景图片了
> 
> @lovelymeng 实测退回到9.9.12-25493或者以下(应该)就会显示了.退回会吧,运行下安装的,再装下llqqnt(我用的一键项目).各版本可以在手机上Appshare应用找到.

要是知道插件文件所在的位置的话 (可以从LiteLoaderQQNT的设置里的数据目录跳转，找到/plugins/Background)，
修改一下[renderer.js](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/pull/68/files#diff-8a8d77cf15b2eaf50ec617c3603313fe363eaef34d8eb3c20ce12b607da55f04)文件
在第1342行下面插入以下代码，重启一下QQ就行了
```
      #app {
        /* 聊天窗口背景透明 (#65)*/
        .q-miracle-background{
          display: none;
        }
      }
```
已经尝试提交PR了，等作者通过一下了(x

**Comment by Syunk1t** [comment]
> > > 我的新版本QQ也不能显示主界面背景图片了
> > 
> > 
> > @lovelymeng 实测退回到9.9.12-25493或者以下(应该)就会显示了.退回会吧,运行下安装的,再装下llqqnt(我用的一键项目).各版本可以在手机上Appshare应用找到.
> 
> 要是知道插件文件所在的位置的话 (可以从LiteLoaderQQNT的设置里的数据目录跳转，找到/plugins/Background)， 修改一下[renderer.js](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/pull/68/files#diff-8a8d77cf15b2eaf50ec617c3603313fe363eaef34d8eb3c20ce12b607da55f04)文件 在第1342行下面插入以下代码，重启一下QQ就行了
> 
> ```
>       #app {
>         /* 聊天窗口背景透明 (#65)*/
>         .q-miracle-background{
>           display: none;
>         }
>       }
> ```
> 
> 已经尝试提交PR了，等作者通过一下了(x
> 
> 附带一下修改后的截图

我草真的解决了，感谢老哥

**Comment by Artificialheaven** [comment]
> > > 我的新版本QQ也不能显示主界面背景图片了
> > 
> > 
> > @lovelymeng 实测退回到9.9.12-25493或者以下(应该)就会显示了.退回会吧,运行下安装的,再装下llqqnt(我用的一键项目).各版本可以在手机上Appshare应用找到.
> 
> 要是知道插件文件所在的位置的话 (可以从LiteLoaderQQNT的设置里的数据目录跳转，找到/plugins/Background)， 修改一下[renderer.js](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/pull/68/files#diff-8a8d77cf15b2eaf50ec617c3603313fe363eaef34d8eb3c20ce12b607da55f04)文件 在第1342行下面插入以下代码，重启一下QQ就行了
> 
> ```
>       #app {
>         /* 聊天窗口背景透明 (#65)*/
>         .q-miracle-background{
>           display: none;
>         }
>       }
> ```
> 
> 已经尝试提交PR了，等作者通过一下了(x
> 
> 附带一下修改后的截图
> ![QQ_1721884247077](https://private-user-images.githubusercontent.com/22972499/351971396-cdca31c4-6cb9-4649-aa33-7cbc1d61c907.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTEzOTYsIm5iZiI6MTcyMTkxMTA5NiwicGF0aCI6Ii8yMjk3MjQ5OS8zNTE5NzEzOTYtY2RjYTMxYzQtNmNiOS00NjQ5LWFhMzMtN2NiYzFkNjFjOTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDEyMzgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYTMwZTllNTMzMTJkOTM3ZWExZjczY2E4NzMwNTJlNGQ1Y2RkOGRjMzU4YmI5MjU4NDQ3YzdjYmZhYjVkMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FepY7-yMKvnGmIoZ0rCqsq0am3pKcn9qfZWtfQxxtkk)

太强了老哥

**Comment by xh321** [comment]
已发版

**Comment by minecraft4668** [comment]
![image](https://github.com/user-attachments/assets/12cb5c7d-fd79-447a-963f-c85dab06f6f8)
所以作者是不是忘了改manifest.json里的版本号了，导致我在插件列表无法更新

**Comment by xh321** [comment]
> ![image](https://private-user-images.githubusercontent.com/132268400/352248548-12cb5c7d-fd79-447a-963f-c85dab06f6f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTk3NTQsIm5iZiI6MTcyMTk1OTQ1NCwicGF0aCI6Ii8xMzIyNjg0MDAvMzUyMjQ4NTQ4LTEyY2I1YzdkLWZkNzktNDQ3YS05NjNmLWM4NWRhYjA2ZjZmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwMjA0MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjhjOTE2YjdmODA2OWQ3ZTQ0YzExYmJkN2ZmZjUzMDgwMzZlYTJmMTdkYTAwMWNmNzUwZTNhM2EzZWU1MjAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3acMNXs2DODknBj0JumkF--vuOnmhn__3UtQeX7xtlg) 所以作者是不是忘了改manifest.json里的版本号了，导致我在插件列表无法更新

改了呀，你看看现在的版本库

**Comment by AkatsukiZhang** [comment]
> 改了呀，你看看现在的版本库

Release.0.2.20的压缩包里的manifest.json还是0.2.19

**Comment by minecraft4668** [comment]
插件列表有了，有劳各位大佬了~

**Comment by xh321** [comment]
> > 改了呀，你看看现在的版本库
> 
> Release.0.2.20的压缩包里的manifest.json还是0.2.19 用 插件列表插件 更新 会提示 还是旧版(实际已更新)

草，我可能忘记打包了，这就改

**Comment by xh321** [comment]
重新发一个新版
