### ISSUE TITLE
信息气泡颜色问题

### ISSUE THREAD

**Issue by ZHYxulei** [xh321/LiteLoaderQQNT-Background-Plugin#76]
只要是网站链接，链接会变成白色，和气泡颜色一样分辨不出来
![image](https://github.com/user-attachments/assets/61a30c9e-947f-46c4-b6e5-f1c823c1cf3a)
而且用MS theme的强制气泡颜色也无用，还是这个颜色的气泡

**Comment by ZHYxulei** [comment]
目前还发现设置界面的部分功能开关也会把MS theme的主题色改为白色
![image](https://github.com/user-attachments/assets/14b15de6-ca42-4061-bd71-73ff659ec065)
目前目前只有防撤回，轻量工具箱，背景插件没有这个问题。liteloaderQQNT的选项也会变成白色
插件列表
![image](https://github.com/user-attachments/assets/b4b8359d-4869-4c1a-91ca-319b9ed70001)
![image](https://github.com/user-attachments/assets/15f78290-5e31-4629-84e0-0836ed2caaff)
![image](https://github.com/user-attachments/assets/8eef7ca5-c82e-4a6b-8bdd-701835b57c72)
![image](https://github.com/user-attachments/assets/e6681754-d967-4aaa-b997-293fa81e6cf2)

**Comment by xh321** [comment]
你指的是插件兼容性问题吗

**Comment by ZHYxulei** [comment]
> 你指的是插件兼容性问题吗

是的，现在MS theme更新完了强制气泡颜色可以使用了

**Comment by xh321** [comment]
> > 你指的是插件兼容性问题吗
> 
> 是的，现在MS theme更新完了强制气泡颜色可以使用了

没问题的话先关闭issue了
