### ISSUE TITLE
与其他主题会冲突的

### ISSUE THREAD

**Issue by KNQMuzzi** [xh321/LiteLoaderQQNT-Background-Plugin#8]
![image](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/assets/49626345/01cb3540-9ab4-4c3e-ab57-026455797361)
如图示，红框的地方的遮罩似乎有点过（像是两边叠加？）

**Comment by KNQMuzzi** [comment]
主题是MSpring

**Comment by xh321** [comment]
你是说磨砂背景吗，你的预期效果是什么呢

**Comment by xh321** [comment]
更新了一个版本，调高了消息的磨砂背景亮度，可能会好一点？

**Comment by KNQMuzzi** [comment]
好耶!ヾ（✿▽ﾟ▽ﾟ▽）ノ解决了！！
