### ISSUE TITLE
无法从某些api获取图片

### ISSUE THREAD

**Issue by lowconsume** [xh321/LiteLoaderQQNT-Background-Plugin#80]
https://img.r10086.com/
这个网站下列出的所有api都无法获取。
但是edge浏览器可以正常获取图片。
在一个已关闭的issue你提到了可能是由于返回了错误导致的，这个api在edge浏览器下也返回了一些错误
![image](https://github.com/user-attachments/assets/873b0923-69c7-48e4-b009-77441d3f9be5)

**Comment by xh321** [comment]
错误不是在这里显示的，这是浏览器给的改进意见
问题是存在中文路径出现乱码导致无法获取，目前最新版已经修复

**Comment by lowconsume** [comment]
> 错误不是在这里显示的，这是浏览器给的改进意见 问题是存在中文路径出现乱码导致无法获取，目前最新版已经修复

 已将插件、qq本体和LiteLoaderQQNT都更新到最新版本，但还是无法在这个api获取图片。

**Comment by lowconsume** [comment]
![image](https://github.com/user-attachments/assets/5306d306-c174-4cc3-b4be-9090ded14154)怪，我用上了你写的示例为什么也无法获取？这次连报错都没弹出
